[JENKINS-67132] Fix NPE in isUsernameSecret
jenkinsci/credentials-plugin pull request #249
Opened 2021-11-13 12:54 UTC by MarkEWaite

[JENKINS-67132](https://issues.jenkins.io/browse/JENKINS-67132) reports a  null pointer exception reading the nullable field isUsernameSecret.  Check the field for null before returning it as a boolean type.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Did not provide a test.  If one is required, will work on that later

2021-12-09 15:47 UTC, jglick reviewed
How is this reproduced? https://github.com/jenkinsci/credentials-plugin/blob/f09ec61224ef98165ee942349b5c20d670a7820b/src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java#L61 and https://github.com/jenkinsci/credentials-plugin/blob/f09ec61224ef98165ee942349b5c20d670a7820b/src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java#L82-L87 ought to have covered all the possibilities.

2022-01-05 12:39 UTC, daniel-beck commented
Per my comment in https://issues.jenkins.io/browse/JENKINS-67132, visibility of https://github.com/jenkinsci/credentials-plugin/blob/f09ec61224ef98165ee942349b5c20d670a7820b/src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java#L82 might be the cause for https://github.com/search?q=org%3Ajenkinsci+%22extends+UsernamePasswordCredentialsImpl%22&type=code

The report mentions Openshift/Openstack, which could be at a glance `OpenShiftBearerTokenCredentialImpl` and `OpenstackKeystoneV3`.

2022-01-05 14:05 UTC, jglick requested changes
I am preparing a proper fix, with test.

2022-01-05 14:05 UTC, jglick commented on src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
> +        return usernameSecret == null ? false : usernameSecret;
Wrong default.

2022-01-05 15:06 UTC, MarkEWaite commented
Closing this pull request since @jglick will provide a better fix.  Thanks @jglick !

2022-01-05 15:06 UTC, closed without merging